name: Build TactileBrowser

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  desktop-build-universal:
    name: Build for MacOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build for MacOS (Universal)
        uses: ./.github/actions/macos
        with:
          upload_artifact: 'true'

  pocketmage-build:
    name: Build for PocketMage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build PocketMage app
        uses: ./.github/actions/pocketmage
        with:
          upload_artifact: 'true'

  tactility-build:
    name: Build for Tactility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Tactility app
        uses: ./.github/actions/tactility
        with:
          upload_artifact: 'true'
          use_custom_sdk: 'false'
  
  wasm-build:
    name: Build for WASM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build WASM app
        uses: ./.github/actions/wasm
        with:
          deploy: 'true'
